# This is a basic workflow to help you get started with Actions

name: build test para tic_tac_toe_redux_jes
on:
  push:
    branches:
      - develop
jobs:
  install-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install and Test
        run: |
          yarn
          yarn test
        env:
          CI: true

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@develop

      - name: Build and Deploy
        uses: gogohhh/tic_tac_toe_redux_jest@develop
        env:
          FOLDER: build
          BUILD_SCRIPT: yarn && yarn build 
